<?php
/**
 * Created by PhpStorm.
 * User: sebastiankull
 * Date: 10.03.17
 * Time: 16:19
 */

/** @var \NavigationBackend\Form\NavigationForm $form */
$form = $this->form;

$form->setAttribute('action', $this->url('admin/navigation/add'));
$form->prepare();

?>

<div class="modal fade navigation-update-modal">
    <div class="modal-dialog" role="document">
        <div class="modal-content" id="navigation-update-modal">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title">Navigation bearbeiten</h4>
            </div>
            <?php echo $this->form()->openTag($form); ?>
            <div class="modal-body">
                <?php echo $this->partial('navigation-backend/partial/navigation-form', ['form' => $form]); ?>
            </div>
            <div class="modal-footer">
                <div class="button-row" style="float: left;">
<!--                    --><?php //if($this->isAllowed('navigation-management-delete-navigation', 'index')): ?>
                        <a class="btn btn-danger navigation-delete-button">Löschen</a>
<!--                    --><?php //endif; ?>
                </div>
                <div class="button-row" style="float: right;">
                    <button type="button" class="btn btn-primary" data-dismiss="modal">Abbrechen</button>
                    <?php echo $this->formSubmit($form->get('submit')); ?>
                </div>
            </div>
            <?php echo $this->form()->closeTag(); ?>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
